### ISSUE TITLE
runtime error disabling heapster addon

### ISSUE THREAD

**Issue by palmerabollo** [Azure/aks-engine#1215]
**Is this a request for help?**:

Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

---

**What version of aks-engine?**:

v0.32.3

---

**Kubernetes version**:

v0.11.8

**What happened**:

`aks-engine deploy` fails trying to generate the template with "heapster" addon disabled

I've disabled the following addons:

```
        "addons": [
         {
            "name": "heapster",
            "enabled": false
          },
          {
            "name": "kube-heapster-deployment",
            "enabled": false
          },
          ...
```

The addon names are taken from https://github.com/Azure/aks-engine/blob/v0.32.1/pkg/engine/const.go#L79 and https://github.com/Azure/aks-engine/blob/v0.32.1/pkg/engine/const.go#L29.

```
DEBU[0000] Resolving tenantID for subscriptionID: 4b***-***-***-***4
DEBU[0003] Already registered for "Microsoft.Compute"
DEBU[0003] Already registered for "Microsoft.Storage"
DEBU[0003] Already registered for "Microsoft.Network"
DEBU[0022] pki: PKI asset creation took 8.308701s
FATA[0022] error generating template /***/kubernetes-aks.json: runtime error: index out of range - goroutine 1 [running]:
runtime/debug.Stack(0xc0009395b0, 0x14c2500, 0x2582c80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/Azure/aks-engine/pkg/engine.(*TemplateGenerator).GenerateTemplate.func2(0xc00093b9c0, 0xc00093b9a0, 0xc00093b9b0)
	/go/src/github.com/Azure/aks-engine/pkg/engine/template_generator.go:85 +0x6e
panic(0x14c2500, 0x2582c80)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
text/template.errRecover(0xc00093b798)
	/usr/local/go/src/text/template/exec.go:160 +0x1d0
panic(0x14c2500, 0x2582c80)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
text/template.errRecover(0xc00093a3b8)
	/usr/local/go/src/text/template/exec.go:160 +0x1d0
panic(0x14c2500, 0x2582c80)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/Azure/aks-engine/pkg/engine.getAddonFuncMap.func1(0xc00092e861, 0x8, 0x0, 0x0)
	/go/src/github.com/Azure/aks-engine/pkg/engine/engine.go:682 +0xb6
reflect.Value.call(0x146c060, 0xc000290000, 0x13, 0x166dba1, 0x4, 0xc000282180, 0x1, 0x1, 0x1667d60, 0x15ce901, ...)
	/usr/local/go/src/reflect/value.go:447 +0x454
reflect.Value.Call(0x146c060, 0xc000290000, 0x13, 0xc000282180, 0x1, 0x1, 0x184f420, 0xc000548e40, 0x1443360)
	/usr/local/go/src/reflect/value.go:308 +0xa4
text/template.(*state).evalCall(0xc00093a338, 0x15a5840, 0xc0002901e0, 0x99, 0x146c060, 0xc000290000, 0x13, 0x184f1a0, 0xc00001e3c0, 0xc00092e851, ...)
	/usr/local/go/src/text/template/exec.go:695 +0x6bd
text/template.(*state).evalFunction(0xc00093a338, 0x15a5840, 0xc0002901e0, 0x99, 0xc00001e3f0, 0x184f1a0, 0xc00001e3c0, 0xc000282120, 0x2, 0x2, ...)
	/usr/local/go/src/text/template/exec.go:563 +0x172
text/template.(*state).evalCommand(0xc00093a338, 0x15a5840, 0xc0002901e0, 0x99, 0xc00001e3c0, 0x14c28c0, 0x25baa80, 0x99, 0x84f, 0xc000922d00, ...)
	/usr/local/go/src/text/template/exec.go:460 +0x5e9
text/template.(*state).evalPipeline(0xc00093a338, 0x15a5840, 0xc0002901e0, 0x99, 0xc000386240, 0x0, 0x0, 0xc00093a238)
	/usr/local/go/src/text/template/exec.go:429 +0x126
text/template.(*state).walk(0xc00093a338, 0x15a5840, 0xc0002901e0, 0x99, 0x184f0a0, 0xc00001e420)
	/usr/local/go/src/text/template/exec.go:254 +0x49b
text/template.(*state).walk(0xc00093a338, 0x15a5840, 0xc0002901e0, 0x99, 0x184f2e0, 0xc00001e360)
	/usr/local/go/src/text/template/exec.go:262 +0x142
text/template.(*Template).execute(0xc0005488c0, 0x1830760, 0xc0001a4700, 0x15a5840, 0xc0002901e0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:217 +0x215
text/template.(*Template).Execute(0xc0005488c0, 0x1830760, 0xc0001a4700, 0x15a5840, 0xc0002901e0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:200 +0x53
github.com/Azure/aks-engine/pkg/engine.getContainerAddonsString(0xc0003700c0, 0x16807d6, 0x13, 0x0, 0x0)
	/go/src/github.com/Azure/aks-engine/pkg/engine/engine.go:747 +0x704
github.com/Azure/aks-engine/pkg/engine.(*TemplateGenerator).getMasterCustomData(0xc00000c980, 0xc00007baa0, 0x1695b6e, 0x22, 0xc0003700c0, 0x16, 0xc0004d45a0)
	/go/src/github.com/Azure/aks-engine/pkg/engine/template_generator.go:199 +0x3bb
github.com/Azure/aks-engine/pkg/engine.(*TemplateGenerator).getTemplateFuncMap.func68(0xc0003700c0, 0x0, 0x0)
	/go/src/github.com/Azure/aks-engine/pkg/engine/template_generator.go:585 +0x52
reflect.Value.call(0x14615c0, 0xc0004d55e0, 0x13, 0x166dba1, 0x4, 0xc0004d4580, 0x1, 0x1, 0x1667d60, 0x1, ...)
	/usr/local/go/src/reflect/value.go:447 +0x454
reflect.Value.Call(0x14615c0, 0xc0004d55e0, 0x13, 0xc0004d4580, 0x1, 0x1, 0x184f1e0, 0xc0002837a0, 0x1642a20)
	/usr/local/go/src/reflect/value.go:308 +0xa4
text/template.(*state).evalCall(0xc00093b1b0, 0x1642a20, 0xc0003700c0, 0x16, 0x14615c0, 0xc0004d55e0, 0x13, 0x184f1a0, 0xc000782480, 0xc000a2b618, ...)
	/usr/local/go/src/text/template/exec.go:695 +0x6bd
text/template.(*state).evalFunction(0xc00093b1b0, 0x1642a20, 0xc0003700c0, 0x16, 0xc0007824b0, 0x184f1a0, 0xc000782480, 0xc0002837c0, 0x2, 0x2, ...)
	/usr/local/go/src/text/template/exec.go:563 +0x172
text/template.(*state).evalCommand(0xc00093b1b0, 0x1642a20, 0xc0003700c0, 0x16, 0xc000782480, 0x14c28c0, 0x25baa80, 0x99, 0xc00093af70, 0xc00093aff8, ...)
	/usr/local/go/src/text/template/exec.go:460 +0x5e9
text/template.(*state).evalPipeline(0xc00093b1b0, 0x1642a20, 0xc0003700c0, 0x16, 0xc000780d20, 0x0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:429 +0x126
text/template.(*state).walk(0xc00093b1b0, 0x1642a20, 0xc0003700c0, 0x16, 0x184f0a0, 0xc0007824e0)
	/usr/local/go/src/text/template/exec.go:254 +0x49b
text/template.(*state).walk(0xc00093b1b0, 0x1642a20, 0xc0003700c0, 0x16, 0x184f2e0, 0xc0007130b0)
	/usr/local/go/src/text/template/exec.go:262 +0x142
text/template.(*state).walkTemplate(0xc00093b718, 0x1642a20, 0xc0003700c0, 0x16, 0xc000548300)
	/usr/local/go/src/text/template/exec.go:411 +0x23e
text/template.(*state).walk(0xc00093b718, 0x1642a20, 0xc0003700c0, 0x16, 0x184f460, 0xc000548300)
	/usr/local/go/src/text/template/exec.go:267 +0x205
text/template.(*state).walk(0xc00093b718, 0x1642a20, 0xc0003700c0, 0x16, 0x184f2e0, 0xc0007a6480)
	/usr/local/go/src/text/template/exec.go:262 +0x142
text/template.(*state).walkIfOrWith(0xc00093b718, 0xa, 0x1642a20, 0xc0003700c0, 0x16, 0xc000567020, 0xc0007a6210, 0xc0007a6480)
	/usr/local/go/src/text/template/exec.go:295 +0x222
text/template.(*state).walk(0xc00093b718, 0x1642a20, 0xc0003700c0, 0x16, 0x184f2a0, 0xc000548380)
	/usr/local/go/src/text/template/exec.go:259 +0x327
text/template.(*state).walk(0xc00093b718, 0x1642a20, 0xc0003700c0, 0x16, 0x184f2e0, 0xc0007a6120)
	/usr/local/go/src/text/template/exec.go:262 +0x142
text/template.(*state).walkIfOrWith(0xc00093b718, 0xa, 0x1642a20, 0xc0003700c0, 0x16, 0xc000566e40, 0xc0003c81b0, 0xc0007a6120)
	/usr/local/go/src/text/template/exec.go:295 +0x222
text/template.(*state).walk(0xc00093b718, 0x1642a20, 0xc0003700c0, 0x16, 0x184f2a0, 0xc000548400)
	/usr/local/go/src/text/template/exec.go:259 +0x327
text/template.(*state).walk(0xc00093b718, 0x1642a20, 0xc0003700c0, 0x16, 0x184f2e0, 0xc0000b1500)
	/usr/local/go/src/text/template/exec.go:262 +0x142
text/template.(*Template).execute(0xc00031d640, 0x1830760, 0xc0001a4310, 0x1642a20, 0xc0003700c0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:217 +0x215
text/template.(*Template).Execute(0xc00031d640, 0x1830760, 0xc0001a4310, 0x1642a20, 0xc0003700c0, 0xc00001c1a0, 0xc00001c1a0)
	/usr/local/go/src/text/template/exec.go:200 +0x53
text/template.(*Template).ExecuteTemplate(0xc00093b920, 0x1830760, 0xc0001a4310, 0x1681d9a, 0x14, 0x1642a20, 0xc0003700c0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:186 +0x77
github.com/Azure/aks-engine/pkg/engine.(*TemplateGenerator).GenerateTemplate(0xc00000c980, 0xc00007baa0, 0x1673b8e, 0x9, 0x166ffb9, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/Azure/aks-engine/pkg/engine/template_generator.go:99 +0x43a
github.com/Azure/aks-engine/cmd.(*deployCmd).run(0xc0000b2000, 0x0, 0x0)
	/go/src/github.com/Azure/aks-engine/cmd/deploy.go:393 +0x12a
github.com/Azure/aks-engine/cmd.newDeployCmd.func1(0xc000204f00, 0xc0000b6000, 0x0, 0x11, 0x0, 0x0)
	/go/src/github.com/Azure/aks-engine/cmd/deploy.go:86 +0x129
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).execute(0xc000204f00, 0xc000427e60, 0x11, 0x12, 0xc000204f00, 0xc000427e60)
	/go/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000204500, 0xc000205400, 0xc000205180, 0xc000204f00)
	/go/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000204500, 0xc000096008, 0x0)
	/go/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/Azure/aks-engine/main.go:15 +0x74

MSG:
non-zero return code
```

It works if you use a random addon name (it simply ignores it), so I guess it really has something to do with heapster.

**What you expected to happen**:

Kubernetes cluster deployed without heapster.

**How to reproduce it** (as minimally and precisely as possible):

`aks-engine deploy` a cluster with the following addons disabled:

```
         {
            "name": "heapster",
            "enabled": false
          },
          {
            "name": "kube-heapster-deployment",
            "enabled": false
          },
```

Is there any other way to disable heapster? Thank you.

**Comment by munishm** [comment]
assign @munishm

**Comment by munishm** [comment]
Able to create the cluster using aks-engine version 0.32.3 for Kubernetes version 1.11.8 with these 2 addons disabled. 

Tried with a simple cluster definition file. File attached. 
[kubernetes-simple.txt](https://github.com/Azure/aks-engine/files/3152232/kubernetes-simple.txt)

**Comment by palmerabollo** [comment]
Thanks @munishm, let me compare your cluster definition with mine. I'll post the differences I find as soon as possible.

**Comment by palmerabollo** [comment]
The issue might be caused because we compile and run aks-engine in a container. You can use the following Dockerfile to reproduce it:

```Dockerfile
FROM golang:1.11.5-alpine3.9 as build

ENV AKS_VERSION v0.32.3

RUN apk --no-cache add git make bash
RUN git clone https://github.com/Azure/aks-engine.git -b ${AKS_VERSION} --single-branch /go/src/github.com/Azure/aks-engine

WORKDIR /go/src/github.com/Azure/aks-engine
RUN CGO_ENABLED=0 make LDFLAGS='-extldflags "-static"'

FROM alpine:3.9

RUN apk --no-cache add ca-certificates

COPY --from=build /go/src/github.com/Azure/aks-engine/bin/aks-engine /bin/aks-engine

ENTRYPOINT ["/bin/aks-engine"]
```

Then build and run it:

```bash
docker build -t aks-engine:v0.32.3
docker run --rm -it --entrypoint=sh aks-engine:v0.32.3
```

And use `aks-engine deploy`:

```sh
aks-engine deploy \
   --api-model kubernetes-simple.txt \
   --output-directory /tmp/output \
   --location northeurope \
   --auth-method client_secret \
   --client-id ****** \
   --client-secret ****** \
   --subscription-id ****** \
   --resource-group deleteme \
   --debug
```

It fails with the same error every time.

**Comment by palmerabollo** [comment]
Just in case it is useful, it works if you build it with `golang:1.12.4-alpine3.9` instead of `golang:1.11.5-alpine3.9`. It solves the issue for me.
