### ISSUE TITLE
unable to resetServicePrincipalProfile on -ResourceType 'Microsoft.ContainerService/managedClusters'` using Invoke-AzResourceAction

### ISSUE THREAD

**Issue by atul-ram** [Azure/aks-engine#1288]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of aks-engine?**: 13.5

---

**Kubernetes version**: 13.5

**What happened**:
I am using a powershell script to reset service principal credential on a managed cluster .

**What you expected to happen**:
reset service principal credential on managed cluster

**How to reproduce it** (as minimally and precisely as possible):

$version = '2019-02-01'
$action = 'resetServicePrincipalProfile'

$Id = ""
$secret = ""

$parameter = @{ "clientId"  = $Id 
			    "secret"    = $secret
 }

Invoke-AzResourceAction -Action $action -Parameters $parameter -ApiVersion $version -ResourceName $clustername -ResourceType 'Microsoft.ContainerService/managedClusters'` -ResourceGroupName $rgname -Force -Confirm:$false

**Anything else we need to know**:

**Error**  : 
````powershell
Invoke-AzResourceAction : {
  "code": "NotFound",
  "message": "The entity was not found."
 }
At line:1 char:6
+ $act=Invoke-AzResourceAction -Action $action -Parameters $parameter - ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Invoke-AzResourceAction], ErrorResponseMessageException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.InvokAzureResourceActionCmdlet
````
**Detailed Debug**

````powershell
\>
Invoke-AzResourceAction -Action $action -Parameters $parameter -ApiVersion $version -ResourceName $clustername -ResourceType 'Microsoft.ContainerService/managedClusters'` -ResourceGroupName $rgname -Debug -Force -Confirm:$false
DEBUG: 08:57:53 - InvokAzureResourceActionCmdlet begin processing with ParameterSet 'BySubscriptionLevel'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: 08:57:58 - using account id ''...

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Common.Authentication]: Authenticating using Account: '', environment: 'AzureCloud', tenant: ''

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:57:59.2859912Z: 59469726-db1e-476a-bb49-924a39745825 - LoggerBase.cs: ADAL PCL.CoreCLR with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '' is running...


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:57:59.2862204Z: 59469726-db1e-476a-bb49-924a39745825 - LoggerBase.cs: === Token Acquisition started:
        CacheType: null
        Authentication Target: Client
        , Authority Host: login.microsoftonline.com


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Verbose: 2019-05-11T06:57:59.2863486Z: 59469726-db1e-476a-bb49-924a39745825 - LoggerBase.cs: Loading from cache.


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:57:59.2873601Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 7 items to token cache.


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Verbose: 2019-05-11T06:57:59.2874908Z: 59469726-db1e-476a-bb49-924a39745825 - LoggerBase.cs: Looking up cache for a token...


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:57:59.2875793Z: 59469726-db1e-476a-bb49-924a39745825 - LoggerBase.cs: An item matching the requested resource was found in the cache


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:57:59.2876645Z: 59469726-db1e-476a-bb49-924a39745825 - LoggerBase.cs: 18.92138902 minutes left until token in cache expires


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:57:59.2877435Z: 59469726-db1e-476a-bb49-924a39745825 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:57:59.2879121Z: 59469726-db1e-476a-bb49-924a39745825 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 11/05/2019 07:16:54 +00:00


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/{tenantID}/resourceGroups/{rg-name}/providers/Microsoft.ContainerService/managedClusters/{clustername}/resetServicePrincipalProfile?api-version=2019-02-01

Headers:
User-Agent                    : AzurePowershell/v1.0.0,PSVersion/v6.1.3
ParameterSetName              : BySubscriptionLevel
CommandName                   : Invoke-AzResourceAction

Body:
{
  "clientId": "00000000-0000-0000-0000-000000000000",
  "secret": "00000000-0000-0000-0000-000000000000"
}



Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Accepted

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Location                      : https://management.azure.com/subscriptions/{tenantID}/providers/Microsoft.ContainerService/locations/westeurope/operationresults/0c3f8098-323e-42fc-9e67-33f16d41cdcf?api-version=2017-08-31
x-ms-routing-request-id       : WESTEUROPE:20190511T065800Z:cd366708-23b3-46f9-bb62-2dc8e85d2c95
x-ms-ratelimit-remaining-subscription-writes: 1198
Azure-AsyncOperation          : https://management.azure.com/subscriptions/{tenantID}/providers/Microsoft.ContainerService/locations/westeurope/operations/0c3f8098-323e-42fc-9e67-33f16d41cdcf?api-version=2017-08-31
x-ms-correlation-request-id   : cd366708-23b3-46f9-bb62-2dc8e85d2c95
x-ms-request-id               : 0c3f8098-323e-42fc-9e67-33f16d41cdcf
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : nginx
X-Content-Type-Options        : nosniff
Date                          : Sat, 11 May 2019 06:57:59 GMT

Body:
{
  "id": "/subscriptions/{tenantID}/resourcegroups/{rg-name}/providers/Microsoft.ContainerService/managedClusters/{clustername}",
  "location": "westeurope",
  "name": "{clustername}",
  "tags": {
 
  },
  "type": "Microsoft.ContainerService/ManagedClusters",
  "properties": {
    "provisioningState": "RefreshingServicePrincipalProfile",
    "kubernetesVersion": "1.13.5",
    "dnsPrefix": "ragnar01",
    "fqdn": "ragnar01-e7f5553e.hcp.westeurope.azmk8s.io",
    "agentPoolProfiles": [
      {
        "name": "nodepool1",
        "count": 2,
        "vmSize": "Standard_DS1_v2",
        "osDiskSizeGB": 100,
        "vnetSubnetID": "/subscriptions/{tenantID}/resourceGroups/aks-rg/providers/Microsoft.Network/virtualNetworks/{vnet}/subnets/subnet",
        "maxPods": 30,
        "type": "AvailabilitySet",
        "provisioningState": "RefreshingServicePrincipalProfile",
        "orchestratorVersion": "1.13.5",cus
        "osType": "Linux"
      }
    ],
    "linuxProfile": {
      "adminUsername": "aks-user",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa cmgHcqpwRU011SjdqtOmuDLXs2Viaz3KWs+vpm+inh2AfP7v9LdqrZR9l6tCY6bDGjWDgIkHaPm6xbfQ== aks-user"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "{clientID}"
    },
    "addonProfiles": {
      "httpApplicationRouting": {
        "enabled": false,
        "config": null
      },
      "omsagent": {
        "enabled": true,
        "config": {
          "logAnalyticsWorkspaceResourceId": "/subscriptions/{tenantID}/resourceGroups/oms-d-rg/providers/Microsoft.OperationalInsights/workspaces/asderfoms"
        }
      }
    },
    "nodeResourceGroup": "ragnar01-aks-{clustername}-e-rg",
    "enableRBAC": false,
    "networkProfile": {
      "networkPlugin": "azure",
      "serviceCidr": "10.432.254.0/24",
      "dnsServiceIP": "10.432.254.10",
      "dockerBridgeCidr": "172.17.0.1/16"
    }
  }
}



Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Common.Authentication]: Authenticating using Account: '{acountID}', environment: 'AzureCloud', tenant: '3a15904d-3fd9-4256-a753-beb05cdf0c6d'

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:58:00.4523879Z: e6e037cd-680d-4295-922a-39c166b7068a - LoggerBase.cs: ADAL PCL.CoreCLR with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:58:00.4527328Z: e6e037cd-680d-4295-922a-39c166b7068a - LoggerBase.cs: === Token Acquisition started:
        CacheType: null
        Authentication Target: Client
        , Authority Host: login.microsoftonline.com


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Verbose: 2019-05-11T06:58:00.4530659Z: e6e037cd-680d-4295-922a-39c166b7068a - LoggerBase.cs: Loading from cache.


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:58:00.4570802Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 7 items to token cache.


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Verbose: 2019-05-11T06:58:00.4574183Z: e6e037cd-680d-4295-922a-39c166b7068a - LoggerBase.cs: Looking up cache for a token...


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:58:00.4576594Z: e6e037cd-680d-4295-922a-39c166b7068a - LoggerBase.cs: An item matching the requested resource was found in the cache


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:58:00.4579423Z: e6e037cd-680d-4295-922a-39c166b7068a - LoggerBase.cs: 18.9018847033333 minutes left until token in cache expires


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:58:00.4581504Z: e6e037cd-680d-4295-922a-39c166b7068a - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:58:00.4584952Z: e6e037cd-680d-4295-922a-39c166b7068a - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expir
ation Time: 11/05/2019 07:16:54 +00:00


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Common.Authentication]: Authenticating using Account: '{acountID}', environment: 'AzureCloud', tenant: '3a15904d-3fd9-4256-a753-beb05cdf0c6d'

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:59:44.7851328Z: 92315719-0562-47ef-991e-e4b184883e4e - LoggerBase.cs: ADAL PCL.CoreCLR with assembly version '3.19.2.6005', file version '3.19.50302.0
130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:59:44.7853126Z: 92315719-0562-47ef-991e-e4b184883e4e - LoggerBase.cs: === Token Acquisition started:
        CacheType: null
        Authentication Target: Client
        , Authority Host: login.microsoftonline.com


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Verbose: 2019-05-11T06:59:44.7854562Z: 92315719-0562-47ef-991e-e4b184883e4e - LoggerBase.cs: Loading from cache.


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:59:44.7863263Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 7 items to token cache.


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Verbose: 2019-05-11T06:59:44.7864892Z: 92315719-0562-47ef-991e-e4b184883e4e - LoggerBase.cs: Looking up cache for a token...


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:59:44.7865953Z: 92315719-0562-47ef-991e-e4b184883e4e - LoggerBase.cs: An item matching the requested resource was found in the cache


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:59:44.7866965Z: 92315719-0562-47ef-991e-e4b184883e4e - LoggerBase.cs: 17.163071825 minutes left until token in cache expires


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:59:44.7867930Z: 92315719-0562-47ef-991e-e4b184883e4e - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T06:59:44.7869811Z: 92315719-0562-47ef-991e-e4b184883e4e - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 11/05/2019 07:16:54 +00:00


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/{tenantID}/providers/Microsoft.ContainerService/locations/westeurope/operationresults/0c3f8098-323e-42fc-9e67-33f16d41cdcf?
api-version=2017-08-31

Headers:
User-Agent                    : AzurePowershell/v1.0.0,PSVersion/v6.1.3
ParameterSetName              : BySubscriptionLevel
CommandName                   : Invoke-AzResourceAction

Body:




Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Accepted

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Location                      : https://management.azure.com/subscriptions/{tenantID}/providers/Microsoft.ContainerService/locations/westeurope/operationresults/bb8a1
69e-5eb6-4029-8e5a-05b73aee5df5?api-version=2017-08-31
x-ms-ratelimit-remaining-subscription-reads: 11997
x-ms-correlation-request-id   : 14a0cfc6-dbc0-4dd9-90df-85ad30f43bf0
x-ms-request-id               : bb8a169e-5eb6-4029-8e5a-05b73aee5df5
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : nginx
x-ms-routing-request-id       : WESTEUROPE:20190511T065945Z:14a0cfc6-dbc0-4dd9-90df-85ad30f43bf0
X-Content-Type-Options        : nosniff
Date                          : Sat, 11 May 2019 06:59:44 GMT

Body:
{
  "name": "98803f0c-3e32-fc42-9e67-33f16d41cdcf",
  "status": "InProgress",
  "startTime": "2019-05-11T06:58:00.226298Z"
}



Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [Common.Authentication]: Authenticating using Account: '{acountID}', environment: 'AzureCloud', tenant: '3a15904d-3fd9-4256-a753-beb05cdf0c6d'

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T07:02:05.2710733Z: 6e4ad7dc-7c0b-4fa0-b14b-a52c06b4f930 - LoggerBase.cs: ADAL PCL.CoreCLR with assembly version '3.19.2.6005', file version '3.19.50302.0
130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T07:02:05.2717074Z: 6e4ad7dc-7c0b-4fa0-b14b-a52c06b4f930 - LoggerBase.cs: === Token Acquisition started:
        CacheType: null
        Authentication Target: Client
        , Authority Host: login.microsoftonline.com


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Verbose: 2019-05-11T07:02:05.2721180Z: 6e4ad7dc-7c0b-4fa0-b14b-a52c06b4f930 - LoggerBase.cs: Loading from cache.


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T07:02:05.2769932Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 7 items to token cache.


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Verbose: 2019-05-11T07:02:05.2774651Z: 6e4ad7dc-7c0b-4fa0-b14b-a52c06b4f930 - LoggerBase.cs: Looking up cache for a token...


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T07:02:05.2778768Z: 6e4ad7dc-7c0b-4fa0-b14b-a52c06b4f930 - LoggerBase.cs: An item matching the requested resource was found in the cache


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T07:02:05.2782364Z: 6e4ad7dc-7c0b-4fa0-b14b-a52c06b4f930 - LoggerBase.cs: 14.8215464633333 minutes left until token in cache expires


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T07:02:05.2786076Z: 6e4ad7dc-7c0b-4fa0-b14b-a52c06b4f930 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: [ADAL]: Information: 2019-05-11T07:02:05.2791048Z: 6e4ad7dc-7c0b-4fa0-b14b-a52c06b4f930 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 11/05/2019 07:16:54 +00:00


Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/{tenantID}/providers/Microsoft.ContainerService/locations/westeurope/operationresults/bb8a169e-5eb6-4029-8e5a-05b73aee5df5?
api-version=2017-08-31

Headers:
User-Agent                    : AzurePowershell/v1.0.0,PSVersion/v6.1.3
ParameterSetName              : BySubscriptionLevel
CommandName                   : Invoke-AzResourceAction

Body:




Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : f6f52fa4-2d66-4912-ac54-cba4ade00ad5
x-ms-request-id               : 5eab466b-6255-48fe-baac-4e8b27daa5f7
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : nginx
x-ms-routing-request-id       : WESTEUROPE:20190511T070205Z:f6f52fa4-2d66-4912-ac54-cba4ade00ad5
X-Content-Type-Options        : nosniff
Date                          : Sat, 11 May 2019 07:02:04 GMT

Body:
{
  "code": "NotFound",
  "message": "The entity was not found."
}



Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
Invoke-AzResourceAction : {
  "code": "NotFound",
  "message": "The entity was not found."
 }
At line:1 char:1
+ Invoke-AzResourceAction -Action $action -Parameters $parameter -ApiVe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Invoke-AzResourceAction], ErrorResponseMessageException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.InvokAzureResourceActionCmdlet

DEBUG: AzureQoSEvent: CommandName - Invoke-AzResourceAction; IsSuccess - False; Duration - 00:10:32.9490810; Exception - Microsoft.Azure.Commands.ResourceManager.Cmdlets.Entities.ErrorResponse
s.ErrorResponseMessageException: {
  "code": "NotFound",
  "message": "The entity was not found."
 }
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: Finish sending metric.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: 09:08:30 - InvokAzureResourceActionCmdlet end processing.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: 09:08:30 - InvokAzureResourceActionCmdlet end processing.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
\>
\>
\>
````

**Comment by CecileRobertMichon** [comment]
Hi @atul-ram, this seems like an issue for https://github.com/Azure/AKS/issues.
