### ISSUE TITLE
Cannot enable custom extension on master.

### ISSUE THREAD

**Issue by nilo19** [Azure/aks-engine#2734]
**Describe the bug**

I want to enable an extension on master but the deployment failed.

Here's the aks-engine config file

```json
{
    "apiVersion": "vlabs",
    "location": "",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "Kubernetes",
            "orchestratorRelease": "1.17",
            "kubernetesConfig": {
                "networkPolicy": "none",
                "cloudProviderRateLimitQPS": 6,
                "cloudProviderRateLimitBucket": 20,
                "controllerManagerConfig": {
                    "--feature-gates": "CSIInlineVolume=true,LocalStorageCapacityIsolation=true,ServiceNodeExclusion=true",
                    "--configure-cloud-routes": "false",
                    "--profiling": "true"
                },
                "apiServerConfig": {
                    "--enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,AlwaysPullImages",
                    "--profiling": "true"
                },
                "schedulerConfig": {
                    "--profiling": "true"
                }
            }
        },
        "masterProfile": {
            "count": 1,
            "dnsPrefix": "kubemark-master-3",
            "vmSize": "Standard_DS2_v2",
            "extensions": [
                {
                    "name": "disable-cloud-route"
                }
            ]
        },
        "extensionProfiles": [
            {
                "name": "disable-cloud-route",
                "version": "v1",
                "rootURL": "https://raw.githubusercontent.com/nilo19/kubemark-performance-tests-on-azure/master/"
            }
        ],
        "linuxProfile": {
            "adminUsername": "",
            "ssh": {
                "publicKeys": [
                    {
                        "keyData": ""
                    }
                ]
            }
        },
        "servicePrincipalProfile": {
            "clientID": "",
            "secret": ""
        }
    }
}
```

Here's the log during `az group deployment create -g "" --template-file "" --parameters ""`

```log
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/custom.py", line 938, in deploy_arm_template
    return _deploy_arm_template_core(cmd.cli_ctx, resource_group_name=resource_group_name, template_file=template_file,
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/custom.py", line 289, in _deploy_arm_template_core
    return sdk_no_wait(no_wait, smc.deployments.create_or_update, resource_group_name, deployment_name, properties)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/util.py", line 383, in sdk_no_wait
    return func(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2688, in create_or_update
    raw_result = self._create_or_update_initial(
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2642, in _create_or_update_initial
    raise exp
msrestazure.azure_exceptions.CloudError: <unprintable CloudError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/arm.py", line 103, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/arm.py", line 105, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: <unprintable CLIError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 367, in getMessage
    msg = str(self.msg)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/msrestazure/azure_exceptions.py", line 193, in __str__
    return str(self.error)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/msrestazure/azure_exceptions.py", line 120, in __str__
    return error_bytes.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 880: ordinal not in range(128)
Call stack:
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/__main__.py", line 41, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/__main__.py", line 30, in cli_main
    return cli.invoke(args)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/knack/cli.py", line 218, in invoke
    exit_code = self.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 107, in exception_handler
    return handle_exception(ex)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/util.py", line 47, in handle_exception
    logger.error(ex.args[0])
Message: CloudError("The template deployment 'azuredeploy' is not valid according to the validation procedure. The tracking id is '069f379a-de17-4094-bbcc-9c42dbaaae99'. See inner errors for details.")
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/custom.py", line 938, in deploy_arm_template
    return _deploy_arm_template_core(cmd.cli_ctx, resource_group_name=resource_group_name, template_file=template_file,
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/resource/custom.py", line 289, in _deploy_arm_template_core
    return sdk_no_wait(no_wait, smc.deployments.create_or_update, resource_group_name, deployment_name, properties)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/util.py", line 383, in sdk_no_wait
    return func(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2688, in create_or_update
    raw_result = self._create_or_update_initial(
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2642, in _create_or_update_initial
    raise exp
msrestazure.azure_exceptions.CloudError: <unprintable CloudError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/arm.py", line 103, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/arm.py", line 105, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: <unprintable CLIError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/knack/log.py", line 78, in format
    msg = logging.StreamHandler.format(self, record)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 367, in getMessage
    msg = str(self.msg)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/msrestazure/azure_exceptions.py", line 193, in __str__
    return str(self.error)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/msrestazure/azure_exceptions.py", line 120, in __str__
    return error_bytes.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 880: ordinal not in range(128)
Call stack:
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/__main__.py", line 41, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/__main__.py", line 30, in cli_main
    return cli.invoke(args)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/knack/cli.py", line 218, in invoke
    exit_code = self.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 107, in exception_handler
    return handle_exception(ex)
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/util.py", line 47, in handle_exception
    logger.error(ex.args[0])
Message: CloudError("The template deployment 'azuredeploy' is not valid according to the validation procedure. The tracking id is '069f379a-de17-4094-bbcc-9c42dbaaae99'. See inner errors for details.")
Arguments: ()
```

BTW, if I enable flag `singleOrAll` in master profiles, the `aks-engine generate` would fail.

```json
"masterProfile": {
            "count": 1,
            "dnsPrefix": "kubemark-master-3",
            "vmSize": "Standard_DS2_v2",
            "extensions": [
                {
                    "name": "disable-cloud-route",
                    "singleOrAll": "single"
                }
            ]
},
``` 

```bash
aks-engine generate ...
INFO[0000] Generating assets into ...
json: cannot unmarshal number into Go struct field DeploymentARM.copy of type string
```

**Steps To Reproduce**

Create a cluster with a custom extension on master.

**Expected behavior**

The cluster works well.

**AKS Engine version**

v0.46.3

**Kubernetes version**

1.17

**Additional context**

/kind bug

**Comment by devigned** [comment]
@nilo19, the stack trace you are seeing from Azure CLI is probably caused by a bug in the CLI as evidenced by the following:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.79_1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/arm.py", line 103, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'str' object has no attribute 'message'
```

With that said, the deployment is causing an error, which is probably an issue in aks-engine. Since Azure CLI is blowing up before we can see the underlying error, we need to see what is happening at the HTTP level. To get this information, run `az group deployment create --debug --verbose ...`. This will display all of the HTTP level information.

**Beware, there will likely be sensitive information in the debugging output. Please be aware and act accordingly.**

It would be awesome if you could post back with the HTTP response including the error body. This will help us to resolve the issue you are having with aks-engine.

Looks like there is an error tracking this bug in Azure CLI: https://github.com/Azure/azure-cli/issues/12199.

**Comment by nilo19** [comment]
This is HTTP logs after enabling `--debug` and `--verbose`

```log
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/c4528d9e-c99a-48bb-b12d-fde2176a43b8/resourcegroups/t-qini-kubemark-master-3/providers/Microsoft.Resources/deployments/azuredeploy?api-version=2019-07-01 HTTP/1.1" 400 1056
msrest.http_logger : Response status: 400
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-failure-cause': 'gateway'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger :     'x-ms-request-id': '8be207aa-5edc-43f8-a534-cc645835ddb4'
msrest.http_logger :     'x-ms-correlation-request-id': '8be207aa-5edc-43f8-a534-cc645835ddb4'
msrest.http_logger :     'x-ms-routing-request-id': 'JAPANEAST:20200218T014636Z:8be207aa-5edc-43f8-a534-cc645835ddb4'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Tue, 18 Feb 2020 01:46:35 GMT'
msrest.http_logger :     'Content-Length': '1056'
msrest.http_logger : Response content:
msrest.http_logger : {"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'azuredeploy' is not valid according to the validation procedure. The tracking id is '8be207aa-5edc-43f8-a534-cc645835ddb4'. See inner errors for details.","details":[{"code":"QuotaExceeded","message":"Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus2, Current Limit: 100, Current Usage: 100, Additional Required: 2, (Minimum) New Limit Required: 102. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%22c4528d9e-c99a-48bb-b12d-fde2176a43b8%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests."}]}}
msrest.exceptions : The template deployment 'azuredeploy' is not valid according to the validation procedure. The tracking id is '8be207aa-5edc-43f8-a534-cc645835ddb4'. See inner errors for details.
```

It seems that the azure-cli issue isn't the root cause and it complains that my template is invalid.

**Comment by devigned** [comment]
If you examine the error message, you will find the error is caused by your subscription being over quota. Perhaps, resolving that problem will enable you to deploy the template.

**Comment by nilo19** [comment]
> If you examine the error message, you will find the error is caused by your subscription being over quota. Perhaps, resolving that problem will enable you to deploy the template.

yeah, found that too. I am doing the validation. thanks.
