### ISSUE TITLE
Example Template Deployment is not valid according to the validation procedure

### ISSUE THREAD

**Issue by RickyRajinder** [Azure/aks-engine#2788]
**Describe the bug**
When trying to deploy a cluster in `westus` using https://github.com/Azure/aks-engine/blob/master/examples/windows/kubernetes-hybrid.json, I get a validation error and the cause is unclear.

**Steps To Reproduce**

apimodel:
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "hybridk8s",
      "vmSize": "Standard_D2_v3"
    },
    "agentPoolProfiles": [
      {
        "name": "linuxpool1",
        "count": 1,
        "vmSize": "Standard_D2_v3",
        "availabilityProfile": "AvailabilitySet"
      },
      {
        "name": "windowspool2",
        "count": 2,
        "vmSize": "Standard_D2_v3",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows"
      }
    ],
    "windowsProfile": {
      "adminUsername": "",
      "adminPassword": ""
    },
    "linuxProfile": {
      "adminUsername": "",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```
**Expected behavior**
Cluster successfully deployed

**AKS Engine version**
v0.47.0

**Additional context**
The output of  
```
 az group deployment validate --resource-group $RESOURCEGROUP --template-file "_output/mixedk8s/azuredeploy.json" --parameters "_output/mixedk8s/azuredeploy.parameters.json"
``` 
is:
```
{'additional_properties': {}, 'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'deployment_dry_run' is not valid according to the validation procedure. The tracking id is 'f4026afc-b753-4334-80db-abc3ed7bc498'. See inner errors for details.", 'target': None, 'details': [<azure.mgmt.resource.resources.v2019_07_01.models._models_py3.ErrorResponse object at 0x7f8e52c8ce80>], 'additional_info': None}
```
The output of 
```
az group deployment create --name $DEPLOYMENT --resource-group $RESOURCEGROUP --template-file "./_output/mixedk8s/azuredeploy.json" --parameters "./_output/mixedk8s/azuredeploy.parameters.json"
```
is:
```
--- Logging error ---
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 972, in deploy_arm_template
    no_wait=no_wait, aux_subscriptions=aux_subscriptions)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 296, in _deploy_arm_template_core
    return sdk_no_wait(no_wait, smc.deployments.create_or_update, resource_group_name, deployment_name, properties)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 383, in sdk_no_wait
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2695, in create_or_update
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2642, in _create_or_update_initial
    raise exp
msrestazure.azure_exceptions.CloudError: <unprintable CloudError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 103, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 105, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: <unprintable CLIError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/opt/az/lib/python3.6/logging/__init__.py", line 336, in getMessage
    msg = str(self.msg)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 193, in __str__
    return str(self.error)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 120, in __str__
    return error_bytes.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 878: ordinal not in range(128)
Call stack:
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 41, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 30, in cli_main
    return cli.invoke(args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 218, in invoke
    exit_code = self.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 107, in exception_handler
    return handle_exception(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 47, in handle_exception
    logger.error(ex.args[0])
Message: CloudError("The template deployment 'mixed-k8s-deploy' is not valid according to the validation procedure. The tracking id is '6a43483d-389c-4977-8c58-cf07fd36f956'. See inner errors for details.",)
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 972, in deploy_arm_template
    no_wait=no_wait, aux_subscriptions=aux_subscriptions)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 296, in _deploy_arm_template_core
    return sdk_no_wait(no_wait, smc.deployments.create_or_update, resource_group_name, deployment_name, properties)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 383, in sdk_no_wait
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2695, in create_or_update
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py", line 2642, in _create_or_update_initial
    raise exp
msrestazure.azure_exceptions.CloudError: <unprintable CloudError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 103, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'str' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 105, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: <unprintable CLIError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/opt/az/lib/python3.6/site-packages/knack/log.py", line 78, in format
    msg = logging.StreamHandler.format(self, record)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/opt/az/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/opt/az/lib/python3.6/logging/__init__.py", line 336, in getMessage
    msg = str(self.msg)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 193, in __str__
    return str(self.error)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 120, in __str__
    return error_bytes.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 878: ordinal not in range(128)
Call stack:
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 41, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 30, in cli_main
    return cli.invoke(args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 218, in invoke
    exit_code = self.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 107, in exception_handler
    return handle_exception(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 47, in handle_exception
    logger.error(ex.args[0])
Message: CloudError("The template deployment 'mixed-k8s-deploy' is not valid according to the validation procedure. The tracking id is '6a43483d-389c-4977-8c58-cf07fd36f956'. See inner errors for details.",)
Arguments: ()
```

**Comment by aelmanaa** [comment]
Hello @RickyRajinder  just ran into the smae issue. any workaround?
