### ISSUE TITLE
Commit Erased orchestratorProfile in example kubernetes.json

### ISSUE THREAD

**Issue by hazardsec** [Azure/aks-engine#4054]
**Describe the bug**
Someone committed a change here acf7eaa97716a8735bec52426fca1c4f7f4e0fa1 that removed orchestratorProfile from the example kubernetes.json and if that does not exist you get a segmentation fault error.

**Steps To Reproduce**

Download engine, and sample kubernetes.json. Fill in values without adding orchestratorProfile, run an ./aks-engine deploy

**Expected behavior**
N/A

**AKS Engine version**
N/A

**Kubernetes version**
N/A

**Additional context**
I know this isn't a huge deal, but for those new to kubernetes, the error message doesn't reveal much about the problem and it was working before the change 2 days ago. Here is the error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x96c7bf]

goroutine 1 [running]:
github.com/Azure/aks-engine/pkg/api.(*OrchestratorProfile).IsKubernetes(...)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/pkg/api/types.go:1189
github.com/Azure/aks-engine/pkg/api.convertVLabsProperties(0xc0000e6090, 0xc0001e00c0, 0xc0005f7800, 0x0, 0xc0005f7878)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/pkg/api/convertertoapi.go:372 +0x14f
github.com/Azure/aks-engine/pkg/api.ConvertVLabsContainerService(0xc0003ba360, 0x400, 0x1825a20, 0xc000641de0, 0x2)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/pkg/api/convertertoapi.go:121 +0x249
github.com/Azure/aks-engine/pkg/api.(*Apiloader).LoadContainerService(0xc0005f7bd8, 0xc000044700, 0x428, 0x628, 0xc000410a98, 0x5, 0x0, 0x0, 0xc0003ba300, 0x0, ...)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/pkg/api/apiloader.go:214 +0x710
github.com/Azure/aks-engine/pkg/api.(*Apiloader).DeserializeContainerService(0xc0005f7bd8, 0xc000044700, 0x428, 0x628, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/pkg/api/apiloader.go:72 +0x152
github.com/Azure/aks-engine/pkg/api.(*Apiloader).LoadContainerServiceFromFile(0xc0005f7bd8, 0x7ffd722d1159, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/pkg/api/apiloader.go:38 +0x224
github.com/Azure/aks-engine/cmd.(*deployCmd).loadAPIModel(0xc0000381e0, 0xc00062d900, 0xc000400270, 0x0, 0xd, 0x0, 0x0)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/cmd/deploy.go:185 +0xcd
github.com/Azure/aks-engine/cmd.newDeployCmd.func1(0xc00062d900, 0xc000400270, 0x0, 0xd, 0x0, 0x0)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/cmd/deploy.go:80 +0xeb
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).execute(0xc00062d900, 0xc000400000, 0xd, 0xd, 0xc00062d900, 0xc000400000)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00062d180, 0xc00064c000, 0xc00062db80, 0xc00062d900)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).Execute(0xc00062d180, 0xc00000c018, 0x0)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/Users/matt/Projects/src/github.com/Azure/aks-engine/main.go:15 +0x74
[student@sec540]$ ./aks-engine deploy --subscription-id $SUBSCRIPTION_ID --resource-group DevSecOps --location centralus --auto-suffix --client-id 5901de4e-3d32-4424-820a-a01dcda896a1 --client-secret 00e2ee71-d5fc-408a-86de-30853e7707ad --api-model ./kubernetes.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x96c7bf]

goroutine 1 [running]:
github.com/Azure/aks-engine/pkg/api.(*OrchestratorProfile).IsKubernetes(...)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/pkg/api/types.go:1189
github.com/Azure/aks-engine/pkg/api.convertVLabsProperties(0xc0001153b0, 0xc00037e600, 0xc00055b800, 0x0, 0xc00055b878)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/pkg/api/convertertoapi.go:372 +0x14f
github.com/Azure/aks-engine/pkg/api.ConvertVLabsContainerService(0xc0000b6e40, 0x400, 0x1825a20, 0xc0003a6180, 0x2)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/pkg/api/convertertoapi.go:121 +0x249
github.com/Azure/aks-engine/pkg/api.(*Apiloader).LoadContainerService(0xc00055bbd8, 0xc000044700, 0x40f, 0x60f, 0xc0000b0e38, 0x5, 0x0, 0x0, 0xc0000b6de0, 0x0, ...)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/pkg/api/apiloader.go:214 +0x710
github.com/Azure/aks-engine/pkg/api.(*Apiloader).DeserializeContainerService(0xc00055bbd8, 0xc000044700, 0x40f, 0x60f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/pkg/api/apiloader.go:72 +0x152
github.com/Azure/aks-engine/pkg/api.(*Apiloader).LoadContainerServiceFromFile(0xc00055bbd8, 0x7ffdd8184159, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/pkg/api/apiloader.go:38 +0x224
github.com/Azure/aks-engine/cmd.(*deployCmd).loadAPIModel(0xc0000ba0f0, 0xc00021cf00, 0xc0000ab6c0, 0x0, 0xd, 0x0, 0x0)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/cmd/deploy.go:185 +0xcd
github.com/Azure/aks-engine/cmd.newDeployCmd.func1(0xc00021cf00, 0xc0000ab6c0, 0x0, 0xd, 0x0, 0x0)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/cmd/deploy.go:80 +0xeb
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).execute(0xc00021cf00, 0xc0000ab1e0, 0xd, 0xd, 0xc00021cf00, 0xc0000ab1e0)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00021c500, 0xc00021d400, 0xc00021d180, 0xc00021cf00)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).Execute(0xc00021c500, 0xc0000b4008, 0x0)
	/Users/matt/Projects/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/Users/matt/Projects/src/github.com/Azure/aks-engine/main.go:15 +0x74

**Comment by hazardsec** [comment]
May not be an issue in current version. Need to test and reopen if needed. Was testing against old version.
