### ISSUE TITLE
SqlException caused by eth0: Lost carrier and losing DHCP leases

### ISSUE THREAD

**Issue by Psybax** [Azure/aks-engine#4603]
**Describe the bug**
SqlException caused by eth0: Lost carrier and losing DHCP leases.

It's similar to https://github.com/Azure/aks-engine/issues/4341. But I did not see fix updates in this issue.

Log is listed as below.
![image](https://user-images.githubusercontent.com/77722804/127427144-a8507275-3ad8-403e-a618-5072729dba5d.png)
Also we have a SqlException caused by this.
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): Unknown error 258
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__203_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at IdentityServer4.EntityFramework.Stores.ResourceStore.FindApiResourcesByScopeAsync(IEnumerable`1 scopeNames)
   at IdentityServer4.Stores.IResourceStoreExtensions.FindResourcesByScopeAsync(IResourceStore store, IEnumerable`1 scopeNames)
   at IdentityServer4.Validation.ScopeValidator.AreScopesValidAsync(IEnumerable`1 requestedScopes, Boolean filterIdentityScopes)
   at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestedScopesAsync(NameValueCollection parameters, Boolean ignoreImplicitIdentityScopes, Boolean ignoreImplicitOfflineAccess)
   at IdentityServer4.Validation.TokenRequestValidator.ValidateClientCredentialsRequestAsync(NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.RunValidationAsync(Func`2 validationFunc, NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestAsync(NameValueCollection parameters, ClientSecretValidationResult clientValidationResult)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
ClientConnectionId:efe767e8-218c-4d51-83fb-f056458c5873
Error Number:-2,State:0,Class:11
ClientConnectionId before routing:a6ad0d59-0da9-4e7f-b1e2-38bf66b7dc35
Routing Destination:d8f85b48b22e.HS2.tr3529.northeurope1-a.worker.database.windows.net,11001
```
**Steps To Reproduce**

**Expected behavior**
Not expect SqlException
**AKS Engine version**
AKSUbuntu-1804gen2containerd-2021.05.19
**Kubernetes version**
1.19.9
**Additional context**

**Comment by axelgMS** [comment]
given the time of issue, that might be same as https://github.com/Azure/aks-engine/issues/4595

**Comment by Will-Bill** [comment]
I am getting this issue daily. Moving back to windows until linux is fixed.

**Comment by bridgetkromhout** [comment]
As stated in https://github.com/Azure/aks-engine/issues/4341#issuecomment-1072661715 we believe this issue to be resolved. That being said, AKS Engine is also deprecated, so please ensure you move to AKS or CAPZ; thanks.
