### ISSUE TITLE
Load Balancer IP Association failed due to NPE in kube-controller on Windows Nodes

### ISSUE THREAD

**Issue by jawaharjazz** [Azure/aks-engine#4702]
**Public IP Addresses are created as part of the cluster creation. After that, we are using Kubernetes Service to bind the previously created Public IP address with the load balancer. But the binding is failing and can able to see that Kube-controller is not stable in those clusters. We are facing issue recently **

**Steps To Reproduce**

1. create Public IP on the azure portal.
2. Create new Kubernetes service using previously created Public IP address
3. IP association with the load balancer is not happening and able to see the below logs in kube-controller-manager

I1018 07:17:34.607675       1 azure_backoff.go:282] LoadBalancerClient.List(CLUSTER NAME) success
I1018 07:17:34.611893       1 shared_informer.go:247] Caches are synced for HPA
I1018 07:17:34.675176       1 shared_informer.go:247] Caches are synced for disruption
I1018 07:17:34.675199       1 disruption.go:339] Sending events to api server.
I1018 07:17:34.681013       1 azure_backoff.go:298] PublicIPAddressesClient.List(CLUSTER NAME) success
I1018 07:17:34.695650       1 shared_informer.go:247] Caches are synced for ReplicationController
I1018 07:17:34.722618       1 azure_backoff.go:298] PublicIPAddressesClient.List(CLUSTER NAME) success
I1018 07:17:34.750009       1 shared_informer.go:247] Caches are synced for resource quota
I1018 07:17:34.764341       1 azure_backoff.go:298] PublicIPAddressesClient.List(CLUSTER NAME) success
I1018 07:17:34.782045       1 garbagecollector.go:213] syncing garbage collector with updated resources from discovery (attempt 1): added: [/v1, Resource=configmaps /v1, Resource=endpoints /v1, Resource=events /v1, Resource=limitranges /v1, Resource=namespaces /v1, Resource=nodes /v1, Resource=persistentvolumeclaims /v1, Resource=persistentvolumes /v1, Resource=pods /v1, Resource=podtemplates /v1, Resource=replicationcontrollers /v1, Resource=resourcequotas /v1, Resource=secrets /v1, Resource=serviceaccounts /v1, Resource=services admissionregistration.k8s.io/v1, Resource=mutatingwebhookconfigurations admissionregistration.k8s.io/v1, Resource=validatingwebhookconfigurations apiextensions.k8s.io/v1, Resource=customresourcedefinitions apiregistration.k8s.io/v1, Resource=apiservices apps/v1, Resource=controllerrevisions apps/v1, Resource=daemonsets apps/v1, Resource=deployments apps/v1, Resource=replicasets apps/v1, Resource=statefulsets autoscaling/v1, Resource=horizontalpodautoscalers batch/v1, Resource=jobs batch/v1beta1, Resource=cronjobs certificates.k8s.io/v1, Resource=certificatesigningrequests coordination.k8s.io/v1, Resource=leases discovery.k8s.io/v1beta1, Resource=endpointslices events.k8s.io/v1, Resource=events extensions/v1beta1, Resource=ingresses flowcontrol.apiserver.k8s.io/v1beta1, Resource=flowschemas flowcontrol.apiserver.k8s.io/v1beta1, Resource=prioritylevelconfigurations networking.k8s.io/v1, Resource=ingressclasses networking.k8s.io/v1, Resource=ingresses networking.k8s.io/v1, Resource=networkpolicies node.k8s.io/v1, Resource=runtimeclasses policy/v1beta1, Resource=poddisruptionbudgets policy/v1beta1, Resource=podsecuritypolicies rbac.authorization.k8s.io/v1, Resource=clusterrolebindings rbac.authorization.k8s.io/v1, Resource=clusterroles rbac.authorization.k8s.io/v1, Resource=rolebindings rbac.authorization.k8s.io/v1, Resource=roles scheduling.k8s.io/v1, Resource=priorityclasses secrets-store.csi.x-k8s.io/v1alpha1, Resource=secretproviderclasses secrets-store.csi.x-k8s.io/v1alpha1, Resource=secretproviderclasspodstatuses storage.k8s.io/v1, Resource=csidrivers storage.k8s.io/v1, Resource=csinodes storage.k8s.io/v1, Resource=storageclasses storage.k8s.io/v1, Resource=volumeattachments], removed: []
I1018 07:17:34.809440       1 azure_backoff.go:298] PublicIPAddressesClient.List(CLUSTER NAME) success
I1018 07:17:34.853135       1 azure_backoff.go:298] PublicIPAddressesClient.List(CLUSTER NAME) success
E1018 07:17:34.853248       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1594 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3f2eec0, 0x6f5d020)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x3f2eec0, 0x6f5d020)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).serviceOwnsFrontendIP(0xc0001aae00, 0x0, 0xc001bbc9a0, 0xc001e8cb30, 0xc001e8cb60, 0xc001e8ca80, 0x0, 0xc001e8cb50, 0xc000879a40, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_standard.go:370 +0x2a1
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).getServiceLoadBalancerStatus(0xc0001aae00, 0xc000879a40, 0xc001d20f50, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:515 +0x3ba
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).getServiceLoadBalancer(0xc0001aae00, 0xc000879a40, 0x7ffd432a26c2, 0x15, 0xc0005d2100, 0x14, 0x20, 0x1, 0xc000787260, 0x2, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:387 +0x3fd
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).reconcileLoadBalancer(0xc0001aae00, 0x7ffd432a26c2, 0x15, 0xc000879a40, 0xc0005d2100, 0x14, 0x20, 0x1, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:1095 +0x3da
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).EnsureLoadBalancer(0xc0001aae00, 0x4e65720, 0xc000058040, 0x7ffd432a26c2, 0x15, 0xc000879a40, 0xc0005d2100, 0x14, 0x20, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:191 +0x33c
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).ensureLoadBalancer(0xc00116c2d0, 0xc000879a40, 0x0, 0x0, 0x6)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:420 +0xf2
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).syncLoadBalancerIfNeeded(0xc00116c2d0, 0xc000879a40, 0xc00120aef0, 0xc, 0xc001475cb0, 0x145d2d3, 0x4ebc960)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:375 +0x948
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).processServiceCreateOrUpdate(0xc00116c2d0, 0xc000879a40, 0xc00120aef0, 0xc, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:311 +0xd9
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).syncService(0xc00116c2d0, 0xc00120aef0, 0xc, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:806 +0x31a
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).processNextWorkItem(0xc00116c2d0, 0x203000)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:269 +0xf5
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).worker(0xc00116c2d0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:258 +0x2b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001fa6020)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001fa6020, 0x4df84c0, 0xc001ac41b0, 0x1, 0xc001494ae0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001fa6020, 0x3b9aca00, 0x0, 0x1, 0xc001494ae0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc001fa6020, 0x3b9aca00, 0xc001494ae0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).Run
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:247 +0x24e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x315c0c1]

goroutine 1594 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x3f2eec0, 0x6f5d020)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).serviceOwnsFrontendIP(0xc0001aae00, 0x0, 0xc001bbc9a0, 0xc001e8cb30, 0xc001e8cb60, 0xc001e8ca80, 0x0, 0xc001e8cb50, 0xc000879a40, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_standard.go:370 +0x2a1
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).getServiceLoadBalancerStatus(0xc0001aae00, 0xc000879a40, 0xc001d20f50, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:515 +0x3ba
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).getServiceLoadBalancer(0xc0001aae00, 0xc000879a40, 0x7ffd432a26c2, 0x15, 0xc0005d2100, 0x14, 0x20, 0x1, 0xc000787260, 0x2, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:387 +0x3fd
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).reconcileLoadBalancer(0xc0001aae00, 0x7ffd432a26c2, 0x15, 0xc000879a40, 0xc0005d2100, 0x14, 0x20, 0x1, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:1095 +0x3da
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).EnsureLoadBalancer(0xc0001aae00, 0x4e65720, 0xc000058040, 0x7ffd432a26c2, 0x15, 0xc000879a40, 0xc0005d2100, 0x14, 0x20, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:191 +0x33c
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).ensureLoadBalancer(0xc00116c2d0, 0xc000879a40, 0x0, 0x0, 0x6)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:420 +0xf2
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).syncLoadBalancerIfNeeded(0xc00116c2d0, 0xc000879a40, 0xc00120aef0, 0xc, 0xc001475cb0, 0x145d2d3, 0x4ebc960)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:375 +0x948
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).processServiceCreateOrUpdate(0xc00116c2d0, 0xc000879a40, 0xc00120aef0, 0xc, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:311 +0xd9
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).syncService(0xc00116c2d0, 0xc00120aef0, 0xc, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:806 +0x31a
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).processNextWorkItem(0xc00116c2d0, 0x203000)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:269 +0xf5
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).worker(0xc00116c2d0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:258 +0x2b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001fa6020)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001fa6020, 0x4df84c0, 0xc001ac41b0, 0x1, 0xc001494ae0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001fa6020, 0x3b9aca00, 0x0, 0x1, 0xc001494ae0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc001fa6020, 0x3b9aca00, 0xc001494ae0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).Run
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:247 +0x24e

**Expected behavior**
Public IP address should be associated with the LB.

**AKS Engine version**
https://github.com/Azure/aks-engine/releases/tag/v0.62.1

**Kubernetes version**
1.20.5

**Additional context - Sample service with loadbalancer IP**

```
apiVersion: v1
kind: Service
metadata:
        name: NAME OF THE `SERVICE`
`spec:`
        ipFamilyPolicy: SingleStack
        ipFamilies: ["IPv4"]
        type: LoadBalancer
        loadBalancerIP: IP ADDRESS GOT FROM STEP 1
        ports:
                - protocol: TCP
                  port: 80
                  targetPort: 80
                  name: http
                - protocol: TCP
                  port: 443
                  targetPort: 443
                  name: https

```

**Comment by jawaharjazz** [comment]
it seems the bug fixed with new kubernetes version. so closing this bug.
