### ISSUE TITLE
Windows node scale panic

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#504]
This happens intermittently, but regularly.

```
INFO[0000] validating...                                
INFO[0004] Name suffix: 20143748                        
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/Azure/aks-engine/cmd.(*scaleCmd).run(0xc0003b2dc0, 0xc000213b80, 0xc000202b40, 0x0, 0x14, 0x0, 0x0)
	/go/src/github.com/Azure/aks-engine/cmd/scale.go:255 +0x25c5
github.com/Azure/aks-engine/cmd.newScaleCmd.func1(0xc000213b80, 0xc000202b40, 0x0, 0x14, 0x0, 0x0)
	/go/src/github.com/Azure/aks-engine/cmd/scale.go:71 +0x52
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).execute(0xc000213b80, 0xc000202a00, 0x14, 0x14, 0xc000213b80, 0xc000202a00)
	/go/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000212500, 0xc000213400, 0xc000213180, 0xc000212f00)
	/go/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/Azure/aks-engine/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000212500, 0xc00000e018, 0x0)
	/go/src/github.com/Azure/aks-engine/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/Azure/aks-engine/main.go:15 +0x74
```

**Comment by PatrickLang** [comment]
@jackfrancis what were the steps needed to cause this? I haven't seen it in the tests run against Kubernetes/Kubernetes that are deployed with aks-engine

**Comment by jackfrancis** [comment]
We have a regular test that creates a cluster from this api model:

```
{   "apiVersion": "vlabs",   "properties": {     "orchestratorProfile": {       "orchestratorType": "Kubernetes"     },     "masterProfile": {       "count": 1,       "dnsPrefix": "",       "vmSize": "Standard_D2_v2"     },     "agentPoolProfiles": [       {         "name": "agentwin",         "count": 3,         "vmSize": "Standard_D2_v2",         "osType": "Windows"       }     ],     "windowsProfile": {       "adminUsername": "azureuser",       "adminPassword": "replacepassword1234$"     },     "linuxProfile": {       "adminUsername": "azureuser",       "ssh": {         "publicKeys": [           {             "keyData": ""           }         ]       }     }, "servicePrincipalProfile": {       "clientId": "",       "secret": ""     }   } }
```

We see the above error on a *scale in* operation (from 3 to 1 nodes)
